version: '3.8'
services:
  facade-service:
    build: ./facade-service
    ports:
      - "8000:8000"
    environment:
      - ROCKET_PORT=8000

  logging-service:
    build: ./logging-service
    ports:
      - "8001:8001"
    environment:
      - ROCKET_PORT=8001

  messages-service:
    build: ./messages-service
    ports:
      - "8002:8002"
    environment:
      - ROCKET_PORT=8002
